### ISSUE TITLE
list field type file read error

### ISSUE THREAD

**Issue by Cronist** [gobezu/k2fields#51]
i read this: https://github.com/gobezu/k2fields/wiki/List-field
but when i upload the sample file to teh tmp folder named "k2fields_list_import.csv"
and select type "list" and UI "select"
and then source = "file" and the file location "tmp/k2fields_list_import.csv"

i got

JFile: :read: File cannot open: /www/www/data/tmp/k2fields_list_import.csv

but when i have a look in tmp folder the name of the file is "k2fields_list_import.csv.imported"

where is my mistake. can u help me please?

i just want to a user selection bu country and the cities of that country.

thanks..

**Comment by gobezu** [comment]
what you have done by placing the import file is that you have initiated the automated importing of the values
if all has gone well you now should see values in your #__k2_extra_fields_list_values table
if you want to use those values please refer to the field type list and look in the Type specific tab for additional settings

please contact me through my website contact form for support
