### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by Giandomenico** [gobezu/k2fields#52]
I installed K2fields on a Joomla 2.5.8 and K2 v2.6.6. 
In the admin I have a very poor performance attempting to make a new field or save it.
Some suggestion ? Thanks

**Comment by gobezu** [comment]
Definitely a pain I myself have felt and needs to be addressed in coming maintenance releases.
I have not given it enough attention though as it only occurs during field creation in the backend, something one is bound to do less frequent.
I have instead focused on some great performance improvements on the rendering side of fields, which combined with caching turned on has become soo much faster.

**Comment by Giandomenico** [comment]
Thanks, any way, for your answer and your relevant contribution.
I will tent again your component.
